import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ChevronDown, ChevronRight } from "lucide-react"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"
import { TaskCard } from "@/components/task-card"
import { formatDate } from "@/lib/utils"
import { ClientSustainmentTypePage } from "./client-sustainment-type-page"

// Add this helper function after the imports
const getDurationInDays = (startDate: string, endDate: string): number => {
  const start = new Date(startDate)
  const end = new Date(endDate)
  const diffTime = Math.abs(end.getTime() - start.getTime())
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24))
}

const sustainmentData = [
  {
    id: 1,
    loe: "LOE 1: Capture Capability Requirements and Current Solutions",
    summary: "Identify mission needs, capability requirements, and current solutions",
    cpmr: { taskCount: 2, health: "Good" },
    iapr: { taskCount: 4, health: "Good" },
    tmtr: { taskCount: 2, health: "At Risk" },
    tasks: [
      {
        id: 1,
        name: "Sustainment Requirements Analysis",
        startDate: "2024-01-20",
        endDate: "2024-03-10",
        description: "Analyze sustainment capability requirements for long-term operations",
        deliverable: "Sustainment Requirements Document",
        status: "In Progress",
        issues: ["Resource allocation pending", "Timeline constraints"],
        owner: "Mike Johnson",
        loeId: "loe-1",
        type: "formal",
        assignedTypes: ["CPMR"],
        internalCoord: ["JS J4", "OSD (Log)"],
        externalCoord: ["Army", "Navy", "USTRANSCOM"],
      },
      {
        id: 2,
        name: "Supply Chain Assessment",
        startDate: "2024-02-01",
        endDate: "2024-04-15",
        description: "Assess supply chain capabilities for sustainment operations",
        deliverable: "Supply Chain Report",
        status: "Planning",
        issues: ["Data availability concerns"],
        owner: "Lisa Chen",
        loeId: "loe-1",
        type: "formal",
        assignedTypes: ["IAPR"],
        internalCoord: ["OSD (Log)", "OSD (MR)"],
        externalCoord: ["Air Force", "USEUCOM"],
      },
      {
        id: 3,
        name: "Technology Sustainment",
        startDate: "2024-02-15",
        endDate: "2024-05-01",
        description: "Evaluate technology sustainment and modernization needs",
        deliverable: "Technology Sustainment Plan",
        status: "Not Started",
        issues: [],
        owner: "David Park",
        loeId: "loe-1",
        type: "formal",
        assignedTypes: ["TMTR"],
        internalCoord: ["OSD(R&E)-MDJO"],
        externalCoord: ["Space Force", "USCYBERCOM"],
      },
      {
        id: 4,
        name: "Logistics Infrastructure Review",
        startDate: "2024-03-01",
        endDate: "2024-05-15",
        description: "Review existing logistics infrastructure for sustainment",
        deliverable: "Infrastructure Assessment",
        status: "Planning",
        issues: ["Access limitations"],
        owner: "Amanda Rodriguez",
        loeId: "loe-1",
        type: "formal",
        assignedTypes: ["IAPR"],
        internalCoord: ["OSD (Log)"],
        externalCoord: ["Marines", "USTRANSCOM"],
      },
    ],
  },
  {
    id: 2,
    loe: "LOE 2: Gap and Current Solutions Health Analysis",
    summary: "Assess gaps, solution health, and programmatic risk",
    cpmr: { taskCount: 3, health: "At Risk" },
    iapr: { taskCount: 2, health: "Good" },
    tmtr: { taskCount: 3, health: "Good" },
    tasks: [
      {
        id: 5,
        name: "Sustainment Gap Analysis",
        startDate: "2024-03-15",
        endDate: "2024-05-30",
        description: "Identify gaps in sustainment capabilities and infrastructure",
        deliverable: "Sustainment Gap Report",
        status: "Planning",
        issues: ["Coordination challenges"],
        owner: "Jennifer Adams",
        loeId: "loe-2",
        type: "formal",
        assignedTypes: ["CPMR"],
        internalCoord: ["JS J4", "OSD (Log)"],
        externalCoord: ["Marines", "USINDOPACOM"],
      },
      {
        id: 6,
        name: "Supply Chain Risk Assessment",
        startDate: "2024-04-01",
        endDate: "2024-06-15",
        description: "Assess risks in sustainment supply chains",
        deliverable: "Supply Chain Risk Report",
        status: "Not Started",
        issues: [],
        owner: "Robert Kim",
        loeId: "loe-2",
        type: "formal",
        assignedTypes: ["IAPR"],
        internalCoord: ["OSD (MR)"],
        externalCoord: ["Navy", "USEUCOM"],
      },
      {
        id: 7,
        name: "Technology Lifecycle Analysis",
        startDate: "2024-04-15",
        endDate: "2024-07-01",
        description: "Analyze technology lifecycle for sustainment systems",
        deliverable: "Technology Lifecycle Report",
        status: "Not Started",
        issues: [],
        owner: "Maria Santos",
        loeId: "loe-2",
        type: "formal",
        assignedTypes: ["TMTR"],
        internalCoord: ["OSD(R&E)-MDJO"],
        externalCoord: ["Air Force", "USSPACECOM"],
      },
    ],
  },
  {
    id: 3,
    loe: "LOE 3: Solutions Options Development",
    summary: "Identify solution options and alternatives to close gaps and mitigate risk",
    cpmr: { taskCount: 1, health: "At Risk" },
    iapr: { taskCount: 3, health: "Good" },
    tmtr: { taskCount: 4, health: "Good" },
    tasks: [
      {
        id: 8,
        name: "Alternative Sustainment Solutions",
        startDate: "2024-05-01",
        endDate: "2024-07-15",
        description: "Research alternative sustainment solutions and approaches",
        deliverable: "Alternative Solutions Report",
        status: "Not Started",
        issues: [],
        owner: "Thomas Wilson",
        loeId: "loe-3",
        type: "formal",
        assignedTypes: ["CPMR"],
        internalCoord: ["JS J4"],
        externalCoord: ["Army", "Marines"],
      },
      {
        id: 9,
        name: "Commercial Sustainment Options",
        startDate: "2024-05-15",
        endDate: "2024-08-01",
        description: "Evaluate commercial sustainment options and partnerships",
        deliverable: "Commercial Options Analysis",
        status: "Not Started",
        issues: [],
        owner: "Sarah Mitchell",
        loeId: "loe-3",
        type: "formal",
        assignedTypes: ["IAPR"],
        internalCoord: ["OSD (MR)"],
        externalCoord: ["Air Force", "Navy"],
      },
      {
        id: 10,
        name: "Innovative Technology Solutions",
        startDate: "2024-06-01",
        endDate: "2024-08-15",
        description: "Identify innovative technology solutions for sustainment",
        deliverable: "Innovation Report",
        status: "Not Started",
        issues: [],
        owner: "Kevin Chang",
        loeId: "loe-3",
        type: "formal",
        assignedTypes: ["TMTR"],
        internalCoord: ["OSD(R&E)-MDJO"],
        externalCoord: ["Space Force", "USCYBERCOM"],
      },
    ],
  },
  {
    id: 4,
    loe: "LOE 4: Synthesize All Risks for Decision Support",
    summary: "Weigh risks and opportunities within the tradespace",
    cpmr: { taskCount: 2, health: "Good" },
    iapr: { taskCount: 2, health: "Good" },
    tmtr: { taskCount: 1, health: "At Risk" },
    tasks: [
      {
        id: 11,
        name: "Sustainment Risk Synthesis",
        startDate: "2024-07-01",
        endDate: "2024-08-30",
        description: "Synthesize all sustainment risks for decision support",
        deliverable: "Risk Synthesis Report",
        status: "Not Started",
        issues: [],
        owner: "Patricia Davis",
        loeId: "loe-4",
        type: "formal",
        assignedTypes: ["CPMR", "IAPR"],
        internalCoord: ["JS J4", "OSD ER&O"],
        externalCoord: ["All Services"],
      },
      {
        id: 12,
        name: "Technology Investment Strategy",
        startDate: "2024-07-15",
        endDate: "2024-09-15",
        description: "Develop technology investment strategy for sustainment",
        deliverable: "Investment Strategy",
        status: "Not Started",
        issues: [],
        owner: "Daniel Lee",
        loeId: "loe-4",
        type: "formal",
        assignedTypes: ["TMTR"],
        internalCoord: ["OSD(R&E)-MDJO"],
        externalCoord: ["Space Force", "USCYBERCOM"],
      },
    ],
  },
]

export function generateStaticParams() {
  return [
    { type: 'cpmr' },
    { type: 'iapr' },
    { type: 'tmtr' },
  ];
}

type Params = { type: string };

export default function SustainmentTypePage({ params }: { params: any }) {
  return <ClientSustainmentTypePage type={params.type} />;
}
